// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeoVsbtim_naJ9rWxttJgzcUPMVK3K_1Q',
    appId: '1:733284564943:web:67ab237508d2443de2dcba',
    messagingSenderId: '733284564943',
    projectId: 'mydiary-projectby-chets',
    authDomain: 'mydiary-projectby-chets.firebaseapp.com',
    storageBucket: 'mydiary-projectby-chets.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYJpoU5Wd0RupcYejFDGDKJ1E8-trsaec',
    appId: '1:733284564943:android:f7fb627498e9b623e2dcba',
    messagingSenderId: '733284564943',
    projectId: 'mydiary-projectby-chets',
    storageBucket: 'mydiary-projectby-chets.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiuG8bzVNmMjObsPT5U7GJHNY7FHUbYzU',
    appId: '1:733284564943:ios:af8d2a50346fbfa4e2dcba',
    messagingSenderId: '733284564943',
    projectId: 'mydiary-projectby-chets',
    storageBucket: 'mydiary-projectby-chets.appspot.com',
    iosBundleId: 'com.example.mydiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiuG8bzVNmMjObsPT5U7GJHNY7FHUbYzU',
    appId: '1:733284564943:ios:d0d3c5710e48512ae2dcba',
    messagingSenderId: '733284564943',
    projectId: 'mydiary-projectby-chets',
    storageBucket: 'mydiary-projectby-chets.appspot.com',
    iosBundleId: 'com.example.mydiary.RunnerTests',
  );
}
